name: mobidatok_test
description: Test work for mobidatok

publish_to: 'none' 

version: 1.0.0+4

environment:
  sdk: '>=2.19.0-214.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.3
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  flutter_riverpod: ^2.0.0
  hooks_riverpod: ^2.0.1
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  go_router: ^5.0.5
  get_it: ^7.2.0
  equatable: ^2.0.5
  state_notifier: ^0.7.2+1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: null
  freezed: ^2.1.1
  json_serializable: ^6.4.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/dummy_data.json